#baseURL = 'https://praveenjana.github.io/sampleblog/git'
baseURL = 'https://65f19535c0f66e0008d55721--praveenjana.netlify.app/'
languageCode = 'en-us'
title = 'Praveen Musings'
# config.toml
theme = 'hugo-theme-stack'

