baseURL = 'https://praveenjana.github.io/sampleblog/'
#baseURL = "/"
languageCode = 'en-us'
title = 'Praveen Musings'
# config.toml
theme = 'hugo-theme-stack'

## Comments
[comments]
enabled = true
provider = "disqus"
disqusShortname = "https-praveenjana-github-io-sampleblog"