baseURL = 'https://praveenjana.github.io/sampleblog/'
#baseURL = "/"
languageCode = 'en-us'
title = 'Praveen Musings'
# config.toml
theme = 'hugo-theme-stack'

[services.disqus]
shortname = "https-praveenjana-github-io-sampleblog"
## Comments
[comments]
    enabled = true
    provider = "disqus"
