#baseURL = 'https://praveenjana.github.io/sampleblog/git'
baseURL = 'https://praveenjana.netlify.app/sampleblog/'
languageCode = 'en-us'
title = 'Praveen Musings'
# config.toml
theme = 'hugo-theme-stack'

